module.exports = {
 arrowParens: "always",
 bracketSpacing: true,
 embeddedLanguageFormatting: "auto",
 htmlWhitespaceSensitivity: "css",
 jsxSingleQuote: false,
 jsxBracketSameLine: true,
 printWidth: 200000,
 proseWrap: "preserve",
 quoteProps: "as-needed",
 requirePragma: false,
 semi: true,
 singleQuote: false,
 tabWidth: 1,
 trailingComma: "es5",
 useTabs: false,
};
